apiVersion: v1
kind: Template
labels:
  template: isolate-unhealthy-pod
  xpaas: 1.2.0
metadata:
  annotations:
    description: Application template for JWS applications built using S2I.
    iconClass: icon-tomcat
    tags: tomcat,tomcat7,java,jboss,xpaas
    version: 1.2.0
  creationTimestamp: null
  name: isolate-unhealthy-pod-template
objects:
- apiVersion: v1
  data:
    ${APPLICATION_NAME}: |
      BLOCK_ISOLATE=false
      MAX_ISOLATE_NUM=2
  kind: ConfigMap
  metadata:
    creationTimestamp: null
    name: ${APPLICATION_NAME}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      description: The web server's http port.
    labels:
      application: ${APPLICATION_NAME}
    name: ${APPLICATION_NAME}
  spec:
    ports:
    - port: 8080
      targetPort: 8080
    selector:
      deploymentConfig: ${APPLICATION_NAME}
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      application: ${APPLICATION_NAME}
    name: ${APPLICATION_NAME}
  spec:
    replicas: 1
    selector:
      deploymentConfig: ${APPLICATION_NAME}
    strategy:
      type: Recreate
    template:
      metadata:
        labels:
          application: ${APPLICATION_NAME}
          deploymentConfig: ${APPLICATION_NAME}
        name: ${APPLICATION_NAME}
      spec:
        containers:
        - env:
          - name: WAR_URI
            value: ${WAR_URI}
          - name: JAVA_TOOL_OPTIONS
            value: ${JAVA_TOOL_OPTIONS}
          - name: JAVA_HOME
            value: ${JAVA_HOME}
          - name: JAVA_VERSION
            value: ${JAVA_VERSION}
          image: registry.example.com:5000/webserver-tomcat7/probe-test-war-deploy:5.0
          imagePullPolicy: Always
          name: ${APPLICATION_NAME}
          ports:
          - containerPort: 8080
            name: http
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          volumeMounts:
          - mountPath: /opt/cfgmap/
            name: ${APPLICATION_NAME}
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        securityContext: {}
        terminationGracePeriodSeconds: 60
        volumes:
        - configMap:
            name: ${APPLICATION_NAME}
          name: ${APPLICATION_NAME}
    test: false
    triggers:
    - type: ConfigChange
parameters:
- description: The name for the application.
  name: APPLICATION_NAME
  required: true
  value: app
- description: 'Custom hostname for http service route.  Leave blank for default hostname,
    e.g.: <application-name>-<project>.<default-domain-suffix>'
  name: HOSTNAME_HTTP
- description: WAR URL FOR DEPLOY
  name: WAR_URI
  value: http://192.168.40.102:8089/wars/echo-web-0.0.1-SNAPSHOT.war
- description: JAVA_TOOL_OPTIONS
  name: JAVA_TOOL_OPTIONS
  value: -Duser.home=/home/jboss
- description: JAVA_HOME
  name: JAVA_HOME
  value: /usr/lib/jvm/java-1.7.0
- description: JAVA_VERSION
  name: JAVA_VERSION
  value: 1.7.0
